[package]
name = "rust-3d-test"
version = "0.1.0"
authors = ["Mathias Johansson <mathias9807@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.0"

